# Generated by Django 6.0.6 on 2026-06-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shikshasetu_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
