# Generated by Django 6.0.6 on 2026-06-25 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shikshasetu_app', '0003_coursevideo_videoprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
