# Generated by Django 6.0.6 on 2026-06-27 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shikshasetu_app', '0005_coursebadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
